[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "2asCsbKNet9BuQpVZCjya3Nfk6N4J6yGWXmZojcDwoTJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/joaog/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
